// routes.js
const apartmentsRoutes      = require('./src/routes/apartments.routes')
const agreementsRoutes      = require('./src/routes/agreements.routes.js')
const buildingsRoutes       = require('./src/routes/buildings.routes')
const contractorsRoutes     = require('./src/routes/contractors.routes')
const contractsRoutes       = require('./src/routes/contracts.routes')
const cotisationsRoutes     = require('./src/routes/cotisations.routes')
const depensesRoutes        = require('./src/routes/depenses.routes')
const devisRoutes           = require('./src/routes/devis.routes')
const historyRoutes         = require('./src/routes/sessions.routes.js')
const missionsRoutes        = require('./src/routes/missions.routes')
const notificationsRoutes   = require('./src/routes/notifications.routes.js')
const packsRoutes           = require('./src/routes/packs.routes')
const partiesCommuneRoutes  = require('./src/routes/partiesCommune.routes')
const permissionsRoutes     = require('./src/routes/permissions.routes.js')
const prestatairesRoutes    = require('./src/routes/prestataires.routes')
const servicesRoutes        = require('./src/routes/services.routes.js')
const serviceRequestsRoutes = require('./src/routes/serviceRequests.routes')
const sitesRoutes           = require('./src/routes/sites.routes')
const staffRoutes           = require('./src/routes/staff.routes')
const tasksRoutes           = require('./src/routes/tasks.routes')
const twoFARoutes           = require('./src/routes/twoFA.routes.js')
const usersRoutes           = require('./src/routes/users.routes')
const welcomeRoutes         = require('./src/routes/welcome.routes')
// Import other routes here...

module.exports = function(app) {
    app.use("/api/apartments",          apartmentsRoutes)
    app.use("/api/agreements",          agreementsRoutes)
    app.use("/api/buildings",           buildingsRoutes)
    app.use("/api/contractors",         contractorsRoutes)
    app.use("/api/contracts",           contractsRoutes)
    app.use("/api/cotisations",         cotisationsRoutes)
    app.use("/api/depenses",            depensesRoutes)
    app.use("/api/devis",               devisRoutes)
    app.use("/api/history",             historyRoutes)
    app.use("/api/missions",            missionsRoutes)
    app.use("/api/notifications",       notificationsRoutes)
    app.use("/api/packs",               packsRoutes)
    app.use("/api/partiesCommune",      partiesCommuneRoutes)
    app.use("/api/permissionsRoutes",   permissionsRoutes)
    app.use("/api/prestataires",        prestatairesRoutes)
    app.use("/api/serviceRequests",     serviceRequestsRoutes)
    app.use("/api/services",            servicesRoutes)
    app.use("/api/sites",               sitesRoutes)
    app.use("/api/staff",               staffRoutes)
    app.use("/api/tasks",               tasksRoutes)
    app.use("/api/twofas",              twoFARoutes)
    app.use("/api/users",               usersRoutes)
    app.use("/api/welcome",             welcomeRoutes)
    // Add other routes here...
};
